### ISSUE TITLE
ifElse 

### ISSUE THREAD

**Issue by twilson63** [twilson63/fun-fp#3]
create a function called `ifElse` in the `logic` section

The ifElse function takes three arguments 

* predicate function - should return a true or false when called
* onTrue function that will be executed when the predicate function returns true
* onFalse function that will be executed when the predicate function return false

Both onTrue and onFalse will receive the value passed into the predicate.

```
defaultBeep = ifElse(isNil, always('beep'), identity)

defaultBeep(null)
#> beep
```

**Comment by aplchian** [comment]
made pull request @twilson63
