### ISSUE TITLE
add invoker and split functions

### ISSUE THREAD

**Issue by twilson63** [twilson63/fun-fp#6]
create a function that takes two arguments, an arity or number of args for a given named function and the named function. The invoker then returns a function that takes the arguments and target as the last param.

This is great for safely executing named functions on objects, for example string.split.

Using the invoker function, you could take a function like split and convert it into a composable function that takes the split character first then the string last and make it curried.

```
const splitByComma = split(',')
```

```
splitByComma('one,two,three')
```

**Comment by aplchian** [comment]
pull request added for invoker

**Comment by twilson63** [comment]
FYI, I think you can reference the issue number in your pull request to link the two
